#define NO_CHANGE                                  00
#define STDBY_TO_FUNCTIONAL_DIAG                   03
#define PWR_READY_TO_PWR_DIAG                      06
#define DRIVE_READY_TO_NORM_OPS                    08
#define NORM_OPS_TO_DISCHARGE_DIAG                 09
#define FAULT_CLASSA_TO_STDBY                      15
#define IGNIT_READY_TO_ADV_DIAG_CLASSA             16
#define FAULT_CLASSA_TO_ADV_DIAG_CLASSA            17
#define FAULT_CLASSB_TO_PWR_READY                  22
#define NORM_OPS_TO_DRIVE_READY                    23
#define PWR_READY_TO_ADV_DIAG_CLASSB               24
#define FAULT_CLASSB_TO_ADV_DIAG_CLASSB            25
#define DRIVE_READY_TO_ADV_DIAG_CLASSB             26
#define FAULT_CLASSB_TO_FAIL_SAFE                  29
#define FAULT_CLASS_B_ADV_DIAG_CLASSA_TO_FAIL_SAFE 31
#define PWR_READY_TO_DRIVE_READY                   35
#define STDBY_TO_ADV_DIAG_CLASSA                   37
#define STDBY_TO_IGNIT_READY                       38
#define ADV_DIAG_CLASSB_TO_PWR_READY               91
#define ADV_DIAG_CLASSA_TO_STDBY                   92
#define FAULT_CLASSB_TO_STDBY                      93
#define IGNIT_READY_TO_STDBY                       94
#define PWR_READY_TO_STDBY                         95
#define DRIVE_READY_TO_STDBY                       96
#define NORM_OPS_TO_STDBY                          97
#define NORM_OPS_TO_PWR_READY                      98
#define DRIVE_READY_TO_PWR_READY                   99